### PR TITLE
Configurability

### PR DESCRIPTION
**Pull request by kedean**
Added configuration options using the built-in argparse library. New options are:
- symbol_set to set one or more symbol sets to use randomly from the archive (e.g. `--symbol_set THICK THIN`), defaults to ASCII
- max_framerate to control the sleep time between redraws, defaults to 100
- color_set to allow choosing which colors to draw with. User can use 'random' to use the old behavior
- min_pipes to set the fewest starting points for the algorithm, defaults to 5
- max_pipes to set the most starting points for the algorithm, defaults to 25

Also modified the exit routine so that it does not trash the terminal on exit.

### CODE REVIEW

**Comment by neeasade** [comment]
perf

**Comment by livibetter** [comment]
@KonradIT could you review this?  (and watch the repo)

@kedean because nature of this issue and even over 100 lines changes, I will be willing to merge this if it gets approval votes.

2018-02-15T10:42:19Z edited: `s/couldn't/could/`

**Comment by livibetter** [comment]
@KonradIT * could

**Comment by livibetter** [comment]
Merging this, even though I'd like to make some changes request, but because this was created nearly two years ago, so I won't be asking and will be doing the changes by myself.

----

@kedean @neeasade I have checked out your GitHub profiles (C, Python, Bash/Shell, and/or AUR packaging), I wonder if you will be interested in joining Pipeseroni. [we are looking for new devs][1].

As you may already know we have several pipes in different languages, currently we are focusing on pipes.sh, pipes.c, and the AUR packaging (yet to get started).  If you have the time and are interested in, please do consider.

[1]: https://github.com/pipeseroni/pipeseroni.github.io/issues/3

**Pull request merged**
